"""API route definitions."""
from __future__ import annotations

ROUTES: list[tuple[str, str, str]] = [
    ("GET",    r"^/api/v1/health$",                  "app.handlers.misc:handle_health"),
    ("GET",    r"^/api/v1/runs$",                    "app.handlers.runs:handle_list_runs"),
    ("POST",   r"^/api/v1/runs$",                    "app.handlers.runs:handle_create_run"),
    ("GET",    r"^/api/v1/runs/[^/]+$",             "app.handlers.runs:handle_get_run"),
    ("DELETE", r"^/api/v1/runs/[^/]+$",             "app.handlers.runs:handle_delete_run"),
    ("POST",   r"^/api/v1/runs/batch-delete$",      "app.handlers.runs:handle_batch_delete_runs"),
    ("POST",   r"^/api/v1/runs/[^/]+/cancel$",      "app.handlers.runs:handle_cancel_run"),
    ("POST",   r"^/api/v1/runs/[^/]+/retry$",       "app.handlers.runs:handle_retry_run"),
    ("POST",   r"^/api/v1/runs/[^/]+/continue$",    "app.handlers.runs:handle_continue_run"),
    ("POST",   r"^/api/v1/runs/[^/]+/skip-testing$","app.handlers.runs:handle_skip_testing"),
    ("GET",    r"^/api/v1/runs/[^/]+/report$",      "app.handlers.reports:handle_get_report"),
    ("GET",    r"^/api/v1/runs/[^/]+/radar\.svg$",  "app.handlers.reports:handle_export_radar_svg"),
    ("GET",    r"^/api/v1/runs/[^/]+/responses$",   "app.handlers.reports:handle_get_responses"),
    ("GET",    r"^/api/v1/runs/[^/]+/scorecard$",   "app.handlers.reports:handle_get_scorecard"),
    ("GET",    r"^/api/v1/runs/[^/]+/extraction-audit$", "app.handlers.reports:handle_get_extraction_audit"),
    ("GET",    r"^/api/v1/runs/[^/]+/theta-report$", "app.handlers.reports:handle_get_theta_report"),
    ("GET",    r"^/api/v1/runs/[^/]+/pairwise$",     "app.handlers.reports:handle_get_pairwise"),
    ("GET",    r"^/api/v1/benchmarks$",              "app.handlers.baselines:handle_benchmarks"),
    ("POST",   r"^/api/v1/baselines$",               "app.handlers.baselines:handle_create_baseline"),
    ("GET",    r"^/api/v1/baselines$",               "app.handlers.baselines:handle_list_baselines"),
    ("POST",   r"^/api/v1/baselines/compare$",       "app.handlers.baselines:handle_compare_baseline"),
    ("DELETE", r"^/api/v1/baselines/[^/]+$",          "app.handlers.baselines:handle_delete_baseline"),
    ("GET",    r"^/api/v1/baselines/[^/]+$",         "app.handlers.baselines:handle_get_baseline"),
    ("POST",   r"^/api/v1/compare-runs$",             "app.handlers.compare:handle_create_compare_run"),
    ("GET",    r"^/api/v1/compare-runs$",            "app.handlers.compare:handle_list_compare_runs"),
    ("GET",    r"^/api/v1/compare-runs/[^/]+$",      "app.handlers.compare:handle_get_compare_run"),
    ("GET",    r"^/api/v1/models/[^/]+/trend$",       "app.handlers.models:handle_model_trend"),
    ("GET",    r"^/api/v1/models/[^/]+/theta-trend$", "app.handlers.models:handle_model_theta_trend"),
    ("GET",    r"^/api/v1/leaderboard$",              "app.handlers.models:handle_leaderboard"),
    ("GET",    r"^/api/v1/theta-leaderboard$",       "app.handlers.models:handle_theta_leaderboard"),
    ("GET",    r"^/api/v1/elo-leaderboard$",         "app.handlers.models:handle_elo_leaderboard"),
    ("GET",    r"^/api/v1/exports/runs\.zip$",       "app.handlers.reports:handle_export_runs_zip"),
    ("POST",   r"^/api/v1/calibration/rebuild$",      "app.handlers.calibration:handle_calibration_rebuild"),
    ("POST",   r"^/api/v1/calibration/snapshot$",    "app.handlers.calibration:handle_calibration_snapshot_only"),
    ("POST",   r"^/api/v1/calibration/replay$",      "app.handlers.calibration:handle_create_calibration_replay"),
    ("GET",    r"^/api/v1/calibration/replay$",      "app.handlers.calibration:handle_list_calibration_replays"),
    ("GET",    r"^/api/v1/calibration/replay/[^/]+$", "app.handlers.calibration:handle_get_calibration_replay"),
    ("POST",   r"^/api/v1/tools/generate-isomorphic$", "app.handlers.misc:handle_generate_isomorphic"),
]
